export const RESTORE_TOKEN = 'RESTORE_TOKEN';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SET_INITIAL_VALUES = 'SET_INITIAL_VALUES';
export const UPDATE_STRIP_VALUE = 'UPDATE_STRIP_VALUE';
export const GET_YOUTUBE_VIDEOS = 'GET_YOUTUBE_VIDEOS';
export const GET_MORE_YOUTUBE_VIDEOS = 'GET_MORE_YOUTUBE_VIDEOS';
